- block:
    - name: composer install
      command:
        cmd: composer install
        chdir: "{{ app_path }}"

    - name: npm install
      command:
        cmd: npm i
        chdir: "{{ app_path }}"

    - stat: "path={{ app_path }}/.env"
      register: env

    - block:
        - name: add .env
          template:
            src: env.j2
            dest: "{{ app_path }}/.env"

        - name: generate key
          command:
            cmd: php artisan key:generate
            chdir: "{{ app_path }}"

      when: not env.stat.exists

    - name: add web-app service
      template:
        src: web-app.service.j2
        dest: /etc/systemd/system/web-app.service

    - name: run web-app service
      systemd:
        name: web-app
        daemon_reload: yes
        enabled: yes
        state: restarted

    - name: add npm-dev service
      template:
        src: npm-dev.service.j2
        dest: /etc/systemd/system/npm-dev.service

    - name: run npm-dev service
      systemd:
        name: npm-dev
        daemon_reload: yes
        enabled: yes
        state: restarted

  become: true
  when: app_path is defined
